export const COMPANY = {
  name: "UStruct",
  fullName: "UStruct Steel Detailing",
  tagline: "Built on Precision.",
  subtitle: "STEEL DETAILING",
  email: "info@ustructdetailing.com",
  whatsapp: "+91 70117 92122",
  whatsappLink: "https://wa.me/917011792122",
  location: "Delhi, India",
  linkedin: "https://linkedin.com/company/ustruct",
};

export const SERVICES = [
  {
    id: 1,
    title: "Structural Steel Detailing",
    slug: "structural-steel",
    icon: "STR",
    description: "Comprehensive shop drawings for structural steel frames — beams, columns, braces, and connections to AISC standards.",
    bullets: [
      "Complete member detailing with accurate dimensions",
      "Connection design per AISC specifications",
      "Material optimization for cost savings",
      "Clash detection through 3D modeling",
    ],
    category: "STRUCTURAL",
  },
  {
    id: 2,
    title: "Miscellaneous Steel Detailing",
    slug: "misc-steel",
    icon: "MSC",
    description: "Stairs, handrails, ladders, catwalks, and architectural steel elements detailed to exact specifications.",
    bullets: [
      "Code-compliant stair and railing designs",
      "Detailed platform and walkway layouts",
      "Custom architectural metalwork detailing",
      "Complete fabrication and installation drawings",
    ],
    category: "MISC",
  },
  {
    id: 3,
    title: "Shop Drawings",
    slug: "shop-drawings",
    icon: "SHD",
    description: "Fabrication-ready shop drawings that go straight to the shop floor — clear, precise, and contractor-approved.",
    bullets: [
      "Detailed piece drawings with all dimensions",
      "Complete bill of materials and cut lists",
      "Bolt and weld specifications",
      "Quality control and fabrication notes",
    ],
    category: "DRAWINGS",
  },
  {
    id: 4,
    title: "GA Drawings",
    slug: "ga-drawings",
    icon: "GAD",
    description: "General arrangement drawings showing member layout, grids, and elevations for coordination and approval.",
    bullets: [
      "Overall project layout and elevations",
      "Member location and grid references",
      "Assembly and connection locations",
      "Coordination with architectural plans",
    ],
    category: "DRAWINGS",
  },
  {
    id: 5,
    title: "Erection Drawings",
    slug: "erection-drawings",
    icon: "ERC",
    description: "Field erection plans with piece marks, sequence, and field connection details for efficient site erection.",
    bullets: [
      "Piece mark plans and elevations",
      "Shipping and erection sequences",
      "Anchor bolt and base plate details",
      "Field assembly instructions",
    ],
    category: "DRAWINGS",
  },
  {
    id: 6,
    title: "Connection Details",
    slug: "connection-details",
    icon: "CON",
    description: "Moment, shear, and axial connection designs detailed and drawn to resist specified loads per AISC.",
    bullets: [
      "Standard and custom connection designs",
      "Bolt patterns and weld specifications",
      "Load transfer calculations",
      "Code-compliant detailing",
    ],
    category: "STRUCTURAL",
  },
  {
    id: 7,
    title: "Tekla 3D Modeling",
    slug: "tekla-modeling",
    icon: "TKL",
    description: "Full LOD 400 3D models in Tekla Structures — the industry standard for steel BIM.",
    bullets: [
      "Intelligent 3D parametric modeling",
      "Automated drawing generation",
      "Accurate material quantities",
      "Clash detection and resolution",
    ],
    category: "BIM",
  },
  {
    id: 8,
    title: "BIM Coordination",
    slug: "bim-coordination",
    icon: "BIM",
    description: "Multi-discipline BIM coordination, clash detection, and IFC model federation for seamless project delivery.",
    bullets: [
      "Multi-discipline coordination",
      "Clash detection and resolution",
      "IFC model exchange",
      "Construction sequencing",
    ],
    category: "BIM",
  },
];

export const STATS = [
  { value: "100%",  label: "Accuracy Rate",       description: "Zero rework guarantee" },
  { value: "100+",  label: "Projects Completed",  description: "Globally delivered" },
  { value: "2.5M+", label: "Sq Ft Detailed",      description: "Structural steel area" },
  { value: "10+",   label: "Years Experience",     description: "Combined team expertise" },
];

export const PROCESS_STEPS = [
  {
    number: "01",
    title: "Receive IFC / Contract Drawings",
    description: "You send us your IFC, Revit, PDF, or CAD contract drawings. We review the full scope, raise any clarifications, and confirm the deliverable list — all within 4 business hours of receipt.",
    detail: "Accepted formats: IFC, RVT, DWG, DXF, PDF. We work with whatever your EOR provides.",
  },
  {
    number: "02",
    title: "Tekla Modeling",
    description: "Our Tekla-certified engineers build a precise, fully parametric 3D model in Tekla Structures — every beam, column, connection, and plate modeled to LOD 400 accuracy.",
    detail: "Tekla Structures is the industry standard for steel BIM. Our models drive all downstream drawings automatically.",
  },
  {
    number: "03",
    title: "Fabrication Drawings",
    description: "Shop drawings, GA drawings, erection plans, and connection details are generated directly from the 3D model. No manual redraw — every dimension, weld, and bolt is model-driven.",
    detail: "Deliverables include shop drawings, GA drawings, erection drawings, and connection details per AISC 360-22.",
  },
  {
    number: "04",
    title: "Final Delivery",
    description: "Your complete drawing package is delivered in DXF, DWG, PDF, and Tekla native formats. A senior engineer checks every sheet against the model before release. Revisions are handled promptly.",
    detail: "Typical delivery: DXF + DWG for fabrication, PDF for approval, IFC + native Tekla for BIM coordination.",
  },
];

export const WHY_US = [
  {
    title: "USA Timezone Sync",
    description: "Our team syncs across time zones for real-time coordination — not next-day email.",
    accent: "#1E90FF",
  },
  {
    title: "AISC 360-22 Standards",
    description: "Every connection, every drawing — designed and detailed per AISC 360-22 and IBC.",
    accent: "#FF6B1A",
  },
  {
    title: "98% First-Pass Accuracy",
    description: "60-point internal QA checklist. We find it before your engineer does.",
    accent: "#FF6B1A",
  },
  {
    title: "40% Cost Savings",
    description: "Premium USA-grade quality at a fraction of domestic detailing costs. No compromise.",
    accent: "#1E90FF",
  },
  {
    title: "Tekla Structures Only",
    description: "We use one tool and we use it perfectly. No AutoCAD workarounds — pure Tekla LOD 400.",
    accent: "#FF6B1A",
  },
  {
    title: "Round-the-Clock Support",
    description: "We provide support across time zones to make sure your project never waits.",
    accent: "#1E90FF",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    quote: "UStruct delivered our 200,000 sq ft warehouse steel package with flawless accuracy — not a single RFI from our fabricator. This is now our go-to detailing team.",
    author: "David Chen, PE",
    company: "Apex Structural Engineers",
    city: "Chicago, IL",
    active: true,
  },
  {
    id: 2,
    quote: "We switched to UStruct after being burned by another offshore firm. Night and day difference. They understand AISC, they communicate in real time, and their Tekla models are exceptional.",
    author: "Sarah Martinez",
    company: "Ironworks Fabrication Co.",
    city: "Houston, TX",
    active: true,
  },
  {
    id: 3,
    quote: "Three projects in, and I won't use anyone else. The turnaround has changed how we bid work. We can take more jobs knowing detailing won't be the bottleneck.",
    author: "Mike Thompson",
    company: "Thompson Steel & Construction",
    city: "Atlanta, GA",
    active: true,
  },
];

export const PROJECTS = [
  {
    id: 1,
    title: "Structural Steel Package",
    location: "Chicago, IL",
    type: "INDUSTRIAL",
    scope: "450,000 sq ft warehouse · Tekla 3D · 180 shop drawings",
    imageUrl: "/portfolio/structure/MODEL_SNAP.png",
    tags: ["Tekla Model", "Shop Drawings", "Erection Plan"],
    active: true,
  },
  {
    id: 2,
    title: "Houston Office Tower",
    location: "Houston, TX",
    type: "COMMERCIAL",
    scope: "18-story steel frame · Moment connections · BIM coordination",
    imageUrl: "/portfolio/structure/MODEL_SNAP1.png",
    tags: ["Moment Frame", "BIM", "AISC"],
    active: true,
  },
  {
    id: 3,
    title: "Miscellaneous Steel Package",
    location: "Atlanta, GA",
    type: "INDUSTRIAL",
    scope: "Stairs · Handrails · Catwalks · Mezzanine",
    imageUrl: "/portfolio/misc/MISC.png",
    tags: ["Misc Steel", "Stair", "Handrail"],
    active: true,
  },
  {
    id: 4,
    title: "Dallas Mixed-Use Tower",
    location: "Dallas, TX",
    type: "MIXED-USE",
    scope: "Composite deck · Transfer beams · Connection details",
    imageUrl: "/portfolio/structure/MODEL_SNAP2.png",
    tags: ["Composite Deck", "Transfer Beams", "High-Rise"],
    active: true,
  },
  {
    id: 5,
    title: "Stair & Railing System",
    location: "Phoenix, AZ",
    type: "INDUSTRIAL",
    scope: "Stair stringers · Guardrails · Grating floors",
    imageUrl: "/portfolio/misc/MISC1.png",
    tags: ["Stair", "Guardrail", "Misc Steel"],
    active: true,
  },
  {
    id: 6,
    title: "Seattle Office Campus",
    location: "Seattle, WA",
    type: "COMMERCIAL",
    scope: "3-building campus · Seismic SFRS · Full BIM package",
    imageUrl: "/portfolio/structure/MODEL_SNAP3.png",
    tags: ["Seismic", "SFRS", "BIM Package"],
    active: true,
  },
];
